import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ContactForm from './ContactForm'
import Footer from './Footer'
import HeroSection from './HeroSection'
import PageFile from './Land'
import Nav from './Nav'
import Trips from './Trips'

export default function Home() {
  return (
    <div class="container">
      <Head>
        <title>landing page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
<HeroSection />
<PageFile />
<Trips />
<ContactForm />
<Footer />
      
    </div>
  )
}
